config/routes.rb
Rails.application.routes.draw do
  resources :cats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
    validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    before_action :find_cat, only: [:show, :edit, :update, :destroy]
    def index
        @cat = Cat.all
    end
    def new
        @cat = Cat.new
    end
    
    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            redirect_to cats_path, notice: "新增成功"
        else
            render :new
        end
    end
    def show
    end
    def edit
    end
    def update
        if @cat.update(cat_params)
            redirect_to cats_path, notice: "編輯成功"
        else
            render :edit
        end
    end
    def destroy
        @cat.destroy
        redirect_to cats_path, notice: "刪除成功"
    end

    private
    def cat_params
        params.require(:cat).permit(:title, :description, :publish_date)
    end
    def find_cat
        @cat = Cat.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/edit.html.erb
<h1>編輯貓咪</h1>
<% if @cat.errors.any? %>
<ul>
  <% @cat.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %> <%= form_for(@cat) do |c| %>
<div>
  <%= c.label :title, "貓咪名稱" %> <%= c.text_field :title %>
</div>

<div>
  <%= c.label :description, "貓咪說明" %> <%= c.text_area :description %>
</div>

<div>
  <%= c.label :publish_date, "建立日期" %> <%= c.date_field :publish_date %>
</div>
<%= c.submit "送出" %> <% end %>

app/views/cats/index.html.erb
<h1>貓咪</h1>

<%= link_to "新增貓咪", new_cat_path %>
<ul>
  <% @cat.each do |cat| %>
    <li>
      <%= link_to cat.title, cat_path(cat) %>
      <%= link_to "編輯", edit_cat_path(cat) %>
      <%= link_to "刪除", cat_path(cat.id), method: 'delete', data: { confirm: "確認刪除#{cat.title}？" } %>
    </li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<h1>新增貓咪</h1>
<% if @cat.errors.any? %>
<ul>
  <% byebug %> <% @cat.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %> <%= form_for(@cat) do |c| %>
<div>
  <%= c.label :title, "貓咪名稱" %> <%= c.text_field :title %>
</div>

<div>
  <%= c.label :description, "貓咪說明" %> <%= c.text_area :description %>
</div>

<div>
  <%= c.label :publish_date, "建立日期" %> <%= c.date_field :publish_date %>
</div>
<%= c.submit "送出" %> <% end %>

app/views/cats/show.html.erb
<h1>hello cats</h1>
<h1>貓咪 <%= @cat.title %></h1>
<p>關於<%= @cat.description %></p>
<p>建立日期<%= @cat.publish_date %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CAT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= yield %>
  </body>
</html>